import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import StackProvider from "@/providers/StackProvider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // you can adjust weights
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Aana Newa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-sans antialiased`}>
        <StackProvider>
          {children}
        </StackProvider>
      </body>
    </html>
  );
}
