export const dynamic = "force-dynamic";  // ✅ disable caching

import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import StackProvider from "@/providers/StackProvider";
import { cookies } from "next/headers";
import axios from "axios";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Aana Newa",
  description: "Generated by create next app",
};

const API_URL = process.env.NEXT_PUBLIC_API_URL as string;

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  let user = null;

  try {
    const cookieStore = await cookies();
    const tokenCookie = cookieStore.get("token")?.value;

    if (tokenCookie) {
      const res = await axios.get(`${API_URL}/auth/profile`, {
        headers: { cookie: `token=${tokenCookie}`  },
        withCredentials: true,
      });
      user = res.data.user || null;
    }
  } catch (err) {
    user = null;
  }

  return (
    <html lang="en">
      <body className={`${poppins.variable} font-sans antialiased`}>
        <StackProvider initialData={user}>{children}</StackProvider>
      </body>
    </html>
  );
}
